### ISSUE TITLE
Использование head, read.

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/echo-bot#10]
```haskell
    Control.Monad.IO.Class.liftIO $ print (Req.responseBody $ head response :: A.Value)
```

Использование ```head``` недопустимо. Бота легко сломать, если передать число повторов равное 0.
Также в коде присутствует `read`.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/echo-bot/pull/new/10_read
Поправила, в двух местах был read
