### ISSUE TITLE
Логи

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/echo-bot#17]
Логи выводятся в терминал, но в файл не пишутся.

**Comment by polina-nn** [comment]
Доброе утро! Поясните, пожалуйста, у Вас все логи не выводятся в файл? Я не могу воспроизвести данную ошибку.
Если открыть файл логов после останова бота (останов при нажатии "ctrl C") то все логи на месте. У меня macOS 10.13.6
Может нужно добавить проверку прав? но тут мы не встрянем в зависимость, что у пользователя винда или unix системы?  
Если не выводятся только вот эти логи:
![Снимок экрана 2022-12-08 в 21 46 21](https://user-images.githubusercontent.com/55196536/206540985-601256a8-7da9-4dc1-a91e-d5554bc04699.png)
то это из-за того, что они пишутся до создания Handle, то есть до возможности начала логирования.

**Comment by polina-nn** [comment]
Доброе утро! Поясните, пожалуйста, у Вас все логи не выводятся в файл? Я не могу воспроизвести данную ошибку.
Если открыть файл логов после останова бота (останов при нажатии "ctrl C") то все логи на месте. У меня macOS 10.13.6
Может нужно добавить проверку прав? но тут мы не встрянем в зависимость, что у пользователя винда или unix системы?
Если не выводятся только вот эти логи:

то это из-за того, что они пишутся до создания Handle, то есть до возможности начала логирования.
![Снимок экрана 2022-12-08 в 21 55 12](https://user-images.githubusercontent.com/55196536/206542889-cc807851-ca3e-4e10-a1c3-c940f0a2a1a2.png)

**Comment by pavelzarubin** [comment]
Нет, у меня на убунте не выводятся только те логи, которые должный быть в файле.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/echo-bot/pull/new/17_writing_logs
оказывается у меня тоже логи не писались в случае запуска бинарника.... 
Поправила. Ну и добавила расширение к файлу логов.
