### ISSUE TITLE
Логи при запуске.

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/echo-bot#18]
![Снимок экрана от 2022-12-08 07-01-34](https://user-images.githubusercontent.com/98732727/206353561-542b5d92-4e4d-41a5-905b-2341ed2217c0.png)
Тут что то не так с логами. Почему информация о конфиге и токене выводится столько раз? Конфиг должен быть прочитан один раз при запуске.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/echo-bot/pull/new/18_ReadConfigOnce
Пришлось пересмотреть структуру для главного Handle, которая помогла бы генерировать эталонный Handle в  Map.Map ChatId Handle. Это также позволило не таскать везде токен, поэтому сигнатуры функций стали яснее.

![Снимок экрана 2022-12-08 в 21 40 16](https://user-images.githubusercontent.com/55196536/206539741-a1b6a191-d7f3-4bcf-9167-debc3856a043.png)
