### ISSUE TITLE
Работоспособность бота

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/echo-bot#21]
Сегодня решил потестировать бота. Но почему-то не работает кнопка изменения числа повторов. Она как-будто зависает и ничего не происходит. Можешь проверить у себя?
![Screenshot from 2023-03-01 10-36-06](https://user-images.githubusercontent.com/92144831/222074123-c098d3f9-3c8a-485a-984e-e1d857482ecf.png)

**Comment by polina-nn** [comment]
Вообще мой бот медленно работает. Вот даже видео сняла как он работает на компе, на телефоне гораздо быстрее...

https://user-images.githubusercontent.com/55196536/222121318-57fdad6c-b5c3-4904-b0c4-063aab85b5db.mov

**Comment by roman-bodavskiy** [comment]
Походу это был какой-то глюк со стороны телеграма. Не доходили апдейты с нажатия кнопки. После того, как создал нового бота с новым токеном все норм. Закрываю ишью
