### ISSUE TITLE
расширения Haskell

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/echo-bot#22]
Собственно, то же замечание, что было в сервере https://github.com/polina-nn/news/issues/15

Некоторые безопасные расширения, как `RecordWildCards`, `OverloadedStrings` можно вынести в `package.yaml`
`T.pack` можно убрать во многих местах, а `T.pack $ show` заменить на какой-нибудь синоним, типа 
`showText :: show a => a -> Text`
раз уж мы везде используем `Text`, а не `String`

Вот такие опции лучше убрать `Wno-missing-fields`

**Comment by polina-nn** [comment]
https://github.com/polina-nn/echo-bot/pull/new/22_haskell_extensions
поправила расширения и логирование, опечатки в названиях функций и комментариях
