### ISSUE TITLE
Мелкие замечания по коду

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/echo-bot#24]
1. эта функция в хендлере вроде никогда не возвращает `Nothing`
`hTextFromMessage :: a -> Maybe T.Text`
так что зачем здесь `Maybe`?

2. небольшое дублирование кода
```
        TgTypes.TgInlineKeyboardMarkup
          [ [TgTypes.TgInlineKeyboardButton "1" "1"],
            [TgTypes.TgInlineKeyboardButton "2" "2"],
            [TgTypes.TgInlineKeyboardButton "3" "3"],
            [TgTypes.TgInlineKeyboardButton "4" "4"],
            [TgTypes.TgInlineKeyboardButton "5" "5"]
          ]
```

3. `ckeckSendTgResponse` опечатка

вроде больше ничего такого не нашел

**Comment by polina-nn** [comment]
Добрый день! Исправила
https://github.com/polina-nn/echo-bot/pull/new/24_hTextFromMessage_without_maybe
