### ISSUE TITLE
Файл repeats

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/echo-bot#4]
- [ ] Файл ```repeats``` не должен быть в репозитории, либо должен быть пустым.
- [ ] Почему файл дозаписывается, а не перезаписывается? Нам не нужно хранить историю выборов повторений, для каждого пользователя.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/echo-bot/pull/new/4_repeats
Переделала работу с повторениями, а заодно и всего бота. 
Теперь он использует общую чистую логику для работы консольного и телеграмм бота... 
(У типов уберу лишние поля   и проверку токена&соединения в рамках следующих ишью)

**Comment by polina-nn** [comment]
Прогнала все через hlint и hindent. Hlint попросил новую функцию makeStateRef в main написать из-за повторов кода.
В Config убрались лишние функции, теперь эта инфомация из общей логики поступает.

**Comment by pavelzarubin** [comment]
А PR где?

**Comment by pavelzarubin** [comment]
> https://github.com/polina-nn/echo-bot/pull/new/4_repeats Переделала работу с повторениями, а заодно и всего бота. Теперь он использует общую чистую логику для работы консольного и телеграмм бота... (У типов уберу лишние поля и проверку токена&соединения в рамках следующих ишью)

Вообще переделывать все это плохо. Не будешь же ты на проекте из-за одной таски, весь проект переписывать. Вноси исправления по ишью, а когда перейдем к серверу, можешь перед моей проверкой внести те правки, которые были сделаны для бота.

**Comment by polina-nn** [comment]
Pull Request сделала. 
У меня есть версия, где я только состояние повторения через IOPef сделала.
"Вообще переделывать все это плохо." - абсолютно согласна. 
Так можно не уложится в бюджет проекта и отдел может остаться без премии или с неоплачиваемой работой во вне урочное время. (Я работала главным инженером проекта  -  прекрасно все знаю. И проекты переписывала из-за косяков подчиненных не раз. Особенно когда эксплуатационная документация расходилась с прошедшим экспертизу рабочим проектом.)
Обычно грубые ошибки (не соответствие техническому заданию -  в моем случае - это сохранение числа повторов после окончания работы бота) исправляются на этапе эскизного проектирования. Поэтому, еще раз прошу прощения.
