### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/echo-bot#7]
- [ ] Нет проверки правильности токена.
- [ ] Нет обработки ошибки потери соединения.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/echo-bot/pull/new/7_catchExeptions
Посмотрите, пожалуйста. Такой вариант подойдет? При обнаружении Exeptions главный цикл прерывается (или вообще не запускается) и пишется в лог сообщение. Делала опираясь на книжку Брагилевского, но немного упростила, чтобы опять проект не переписать....
